package com.becasipn.persistence.model;
// Generated 28/10/2016 11:30:51 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import org.eclipse.persistence.annotations.Cache;

/**
 * PadronSubes generated by hbm2java
 */
@Entity
@Table(name = "ENT_PADRON_SUBES")
@Cache(alwaysRefresh = true, type = org.eclipse.persistence.annotations.CacheType.NONE)
public class PadronSubes implements java.io.Serializable, BaseEntity {

	@Id
	@GeneratedValue(generator = "SubesSeq")
    @SequenceGenerator(name = "SubesSeq", sequenceName = "ENT_PADRON_SUBES_id_SEQ", allocationSize = 1)
	private BigDecimal id;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PERIODO_ID")
	private Periodo periodo;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ALUMNO_ID")
	private Alumno alumno;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "USUARIO_ID")
	private Usuario usuario;
	@ManyToOne //(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONVOCATORIA_ID")
	private ConvocatoriaSubes convocatoriaSubes;
	private String foliosubes;
	private String curp;
	private String nombre;
	private String apellidopaterno;
	private String apellidomaterno;
	private String correoelectronico;
	private String celular;
	private String estadocivil;
	private String entidadnacimiento;
	private String estado;
	private String municipio;
	private String localidad;
	private String colonia;
	private String codigopostal;
	private String calle;
	private String numext;
	private String numint;
	private String plantel;
	private String carrera;
	private String matricula;
	private String estatussubes;
	private Integer integranteshogar;
	private Double ingresototal;
	private String discapacidad;
	private String tieneprospera;
	private String vulnerabilidad;
	private Short tipocruce;
	private Short conotorgamiento;
	private Short dae;
	private Short ese;
	private Short finalizado;
	private String validadoipes;
	private String errorAsignacion;
	private String promedio;
	private String semestre;
	private String regularidad;

	private String foliotransporte;
	private String estatustransporte;
	private String vulnerabilidadtransporte;
	private String validadoipestransporte;
	private String errorAsignacionTransporte;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHACARGA")
	private Date fechacarga;

	@Transient
	private String telefono_fijo;
	@Transient
	private String fecha_nacimiento;
	@Transient
	private String sexo;
	@Transient
	private String nacionalidad;
	@Transient
	private String municipio_con_violencia;
	@Transient
	private String municipio_contra_hambre;
	@Transient
	private String municipio_con_marginacion;
	@Transient
	private String clabe;
	@Transient
	private String ficha_escolar_estado;
	@Transient
	private String ficha_escolar_municipio;
	@Transient
	private String ficha_escolar_institucion;
	@Transient
	private String ficha_escolar_promedio_anterior;
	@Transient
	private String ficha_escolar_total_periodos;
	@Transient
	private String ficha_escolar_tipo_periodo;
	@Transient
	private String ficha_activada;
	@Transient
	private String es_indigena;
	@Transient
	private String comunidad_indigena;
	@Transient
	private String es_padre_o_madre;
	@Transient
	private String alumna_embarazada;
	@Transient
	private String folio_prospera;
	@Transient
	private String gasto_mensual_transporte;
	@Transient
	private String principal_medio_transporte;
	@Transient
	private String tiempo_transporte;
	@Transient
	private String kilometros_transporte;
	@Transient
	private String priorizacion_prospera;
	@Transient
	private String folio_cruce_prospera;
	@Transient
	private String fecha_prospera;
	@Transient
	private String folio_promajoven;
	@Transient
	private String fecha_promajoven;

	public PadronSubes() {
	}

	public PadronSubes(BigDecimal id) {
		this.id = id;
	}

	@Override
	public BigDecimal getId() {
		return this.id;
	}

	@Override
	public void setId(BigDecimal id) {
		this.id = id;
	}

	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	public Alumno getAlumno() {
		return this.alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public ConvocatoriaSubes getConvocatoriaSubes() {
		return this.convocatoriaSubes;
	}

	public void setCatConvocatoriaSubes(ConvocatoriaSubes convocatoriaSubes) {
		this.convocatoriaSubes = convocatoriaSubes;
	}

	public String getFoliosubes() {
		return this.foliosubes;
	}

	public void setFoliosubes(String foliosubes) {
		this.foliosubes = foliosubes;
	}

	public String getCurp() {
		return this.curp;
	}

	public void setCurp(String curp) {
		this.curp = curp;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidopaterno() {
		return this.apellidopaterno;
	}

	public void setApellidopaterno(String apellidopaterno) {
		this.apellidopaterno = apellidopaterno;
	}

	public String getApellidomaterno() {
		return this.apellidomaterno;
	}

	public void setApellidomaterno(String apellidomaterno) {
		this.apellidomaterno = apellidomaterno;
	}

	public String getCorreoelectronico() {
		return this.correoelectronico;
	}

	public void setCorreoelectronico(String correoelectronico) {
		this.correoelectronico = correoelectronico;
	}

	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getEstadocivil() {
		return this.estadocivil;
	}

	public void setEstadocivil(String estadocivil) {
		this.estadocivil = estadocivil;
	}

	public String getEntidadnacimiento() {
		return this.entidadnacimiento;
	}

	public void setEntidadnacimiento(String entidadnacimiento) {
		this.entidadnacimiento = entidadnacimiento;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getLocalidad() {
		return this.localidad;
	}

	public void setLocalidad(String localidad) {
		this.localidad = localidad;
	}

	public String getColonia() {
		return this.colonia;
	}

	public void setColonia(String colonia) {
		this.colonia = colonia;
	}

	public String getCodigopostal() {
		return this.codigopostal;
	}

	public void setCodigopostal(String codigopostal) {
		this.codigopostal = codigopostal;
	}

	public String getCalle() {
		return this.calle;
	}

	public void setCalle(String calle) {
		this.calle = calle;
	}

	public String getNumext() {
		return this.numext;
	}

	public void setNumext(String numext) {
		this.numext = numext;
	}

	public String getNumint() {
		return this.numint;
	}

	public void setNumint(String numint) {
		this.numint = numint;
	}

	public String getPlantel() {
		return this.plantel;
	}

	public void setPlantel(String plantel) {
		this.plantel = plantel;
	}

	public String getCarrera() {
		return this.carrera;
	}

	public void setCarrera(String carrera) {
		this.carrera = carrera;
	}

	public String getMatricula() {
		return this.matricula;
	}

	public void setMatricula(String matricula) {
		this.matricula = matricula;
	}

	public String getEstatussubes() {
		return this.estatussubes;
	}

	public void setEstatussubes(String estatussubes) {
		this.estatussubes = estatussubes;
	}

	public Integer getIntegranteshogar() {
		return this.integranteshogar;
	}

	public void setIntegranteshogar(Integer integranteshogar) {
		this.integranteshogar = integranteshogar;
	}

	public Double getIngresototal() {
		return ingresototal;
	}

	public void setIngresototal(Double ingresototal) {
		this.ingresototal = ingresototal;
	}

	public String getDiscapacidad() {
		return this.discapacidad;
	}

	public void setDiscapacidad(String discapacidad) {
		this.discapacidad = discapacidad;
	}

	public String getTieneprospera() {
		return this.tieneprospera;
	}

	public void setTieneprospera(String tieneprospera) {
		this.tieneprospera = tieneprospera;
	}

	public String getFoliotransporte() {
		return this.foliotransporte;
	}

	public void setFoliotransporte(String foliotransporte) {
		this.foliotransporte = foliotransporte;
	}

	public String getEstatustransporte() {
		return this.estatustransporte;
	}

	public void setEstatustransporte(String estatustransporte) {
		this.estatustransporte = estatustransporte;
	}

	public Short getTipocruce() {
		return this.tipocruce;
	}

	public void setTipocruce(Short tipocruce) {
		this.tipocruce = tipocruce;
	}

	public Short getConotorgamiento() {
		return this.conotorgamiento;
	}

	public void setConotorgamiento(Short conotorgamiento) {
		this.conotorgamiento = conotorgamiento;
	}

	public Short getDae() {
		return this.dae;
	}

	public void setDae(Short dae) {
		this.dae = dae;
	}

	public Short getEse() {
		return this.ese;
	}

	public void setEse(Short ese) {
		this.ese = ese;
	}

	public Short getFinalizado() {
		return this.finalizado;
	}

	public void setFinalizado(Short finalizado) {
		this.finalizado = finalizado;
	}

	public String getVulnerabilidad() {
		return vulnerabilidad;
	}

	public void setVulnerabilidad(String vulnerabilidad) {
		this.vulnerabilidad = vulnerabilidad;
	}

	public Date getFechacarga() {
		return this.fechacarga;
	}

	public void setFechacarga(Date fechacarga) {
		this.fechacarga = fechacarga;
	}

	public String getTelefono_fijo() {
		return telefono_fijo;
	}

	public void setTelefono_fijo(String telefono_fijo) {
		this.telefono_fijo = telefono_fijo;
	}

	public String getFecha_nacimiento() {
		return fecha_nacimiento;
	}

	public void setFecha_nacimiento(String fecha_nacimiento) {
		this.fecha_nacimiento = fecha_nacimiento;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getNacionalidad() {
		return nacionalidad;
	}

	public void setNacionalidad(String nacionalidad) {
		this.nacionalidad = nacionalidad;
	}

	public String getMunicipio_con_violencia() {
		return municipio_con_violencia;
	}

	public void setMunicipio_con_violencia(String municipio_con_violencia) {
		this.municipio_con_violencia = municipio_con_violencia;
	}

	public String getMunicipio_contra_hambre() {
		return municipio_contra_hambre;
	}

	public void setMunicipio_contra_hambre(String municipio_contra_hambre) {
		this.municipio_contra_hambre = municipio_contra_hambre;
	}

	public String getMunicipio_con_marginacion() {
		return municipio_con_marginacion;
	}

	public void setMunicipio_con_marginacion(String municipio_con_marginacion) {
		this.municipio_con_marginacion = municipio_con_marginacion;
	}

	public String getClabe() {
		return clabe;
	}

	public void setClabe(String clabe) {
		this.clabe = clabe;
	}

	public String getFicha_escolar_estado() {
		return ficha_escolar_estado;
	}

	public void setFicha_escolar_estado(String ficha_escolar_estado) {
		this.ficha_escolar_estado = ficha_escolar_estado;
	}

	public String getFicha_escolar_municipio() {
		return ficha_escolar_municipio;
	}

	public void setFicha_escolar_municipio(String ficha_escolar_municipio) {
		this.ficha_escolar_municipio = ficha_escolar_municipio;
	}

	public String getFicha_escolar_institucion() {
		return ficha_escolar_institucion;
	}

	public void setFicha_escolar_institucion(String ficha_escolar_institucion) {
		this.ficha_escolar_institucion = ficha_escolar_institucion;
	}

	public String getFicha_escolar_promedio_anterior() {
		return ficha_escolar_promedio_anterior;
	}

	public void setFicha_escolar_promedio_anterior(String ficha_escolar_promedio_anterior) {
		this.ficha_escolar_promedio_anterior = ficha_escolar_promedio_anterior;
	}

	public String getFicha_escolar_total_periodos() {
		return ficha_escolar_total_periodos;
	}

	public void setFicha_escolar_total_periodos(String ficha_escolar_total_periodos) {
		this.ficha_escolar_total_periodos = ficha_escolar_total_periodos;
	}

	public String getFicha_escolar_tipo_periodo() {
		return ficha_escolar_tipo_periodo;
	}

	public void setFicha_escolar_tipo_periodo(String ficha_escolar_tipo_periodo) {
		this.ficha_escolar_tipo_periodo = ficha_escolar_tipo_periodo;
	}

	public String getFicha_activada() {
		return ficha_activada;
	}

	public void setFicha_activada(String ficha_activada) {
		this.ficha_activada = ficha_activada;
	}

	public String getValidadoipes() {
		return validadoipes;
	}

	public void setValidadoipes(String validadoipes) {
		this.validadoipes = validadoipes;
	}

	public String getEs_indigena() {
		return es_indigena;
	}

	public void setEs_indigena(String es_indigena) {
		this.es_indigena = es_indigena;
	}

	public String getComunidad_indigena() {
		return comunidad_indigena;
	}

	public void setComunidad_indigena(String comunidad_indigena) {
		this.comunidad_indigena = comunidad_indigena;
	}

	public String getEs_padre_o_madre() {
		return es_padre_o_madre;
	}

	public void setEs_padre_o_madre(String es_padre_o_madre) {
		this.es_padre_o_madre = es_padre_o_madre;
	}

	public String getAlumna_embarazada() {
		return alumna_embarazada;
	}

	public void setAlumna_embarazada(String alumna_embarazada) {
		this.alumna_embarazada = alumna_embarazada;
	}

	public String getFolio_prospera() {
		return folio_prospera;
	}

	public void setFolio_prospera(String folio_prospera) {
		this.folio_prospera = folio_prospera;
	}

	public String getGasto_mensual_transporte() {
		return gasto_mensual_transporte;
	}

	public void setGasto_mensual_transporte(String gasto_mensual_transporte) {
		this.gasto_mensual_transporte = gasto_mensual_transporte;
	}

	public String getPrincipal_medio_transporte() {
		return principal_medio_transporte;
	}

	public void setPrincipal_medio_transporte(String principal_medio_transporte) {
		this.principal_medio_transporte = principal_medio_transporte;
	}

	public String getTiempo_transporte() {
		return tiempo_transporte;
	}

	public void setTiempo_transporte(String tiempo_transporte) {
		this.tiempo_transporte = tiempo_transporte;
	}

	public String getKilometros_transporte() {
		return kilometros_transporte;
	}

	public void setKilometros_transporte(String kilometros_transporte) {
		this.kilometros_transporte = kilometros_transporte;
	}

	public String getPriorizacion_prospera() {
		return priorizacion_prospera;
	}

	public void setPriorizacion_prospera(String priorizacion_prospera) {
		this.priorizacion_prospera = priorizacion_prospera;
	}

	public String getFolio_cruce_prospera() {
		return folio_cruce_prospera;
	}

	public void setFolio_cruce_prospera(String folio_cruce_prospera) {
		this.folio_cruce_prospera = folio_cruce_prospera;
	}

	public String getFecha_prospera() {
		return fecha_prospera;
	}

	public void setFecha_prospera(String fecha_prospera) {
		this.fecha_prospera = fecha_prospera;
	}

	public String getFolio_promajoven() {
		return folio_promajoven;
	}

	public void setFolio_promajoven(String folio_promajoven) {
		this.folio_promajoven = folio_promajoven;
	}

	public String getFecha_promajoven() {
		return fecha_promajoven;
	}

	public void setFecha_promajoven(String fecha_promajoven) {
		this.fecha_promajoven = fecha_promajoven;
	}

	public String getErrorAsignacion() {
		return errorAsignacion;
	}

	public void setErrorAsignacion(String errorAsignacion) {
		this.errorAsignacion = errorAsignacion;
	}

	public String getPromedio() {
		return promedio;
	}

	public void setPromedio(String promedio) {
		this.promedio = promedio;
	}

	public String getSemestre() {
		return semestre;
	}

	public void setSemestre(String semestre) {
		this.semestre = semestre;
	}

	public String getRegularidad() {
		return regularidad;
	}

	public void setRegularidad(String regularidad) {
		this.regularidad = regularidad;
	}

	public String getVulnerabilidadtransporte() {
		return vulnerabilidadtransporte;
	}

	public void setVulnerabilidadtransporte(String vulnerabilidadtransporte) {
		this.vulnerabilidadtransporte = vulnerabilidadtransporte;
	}

	public String getValidadoipestransporte() {
		return validadoipestransporte;
	}

	public void setValidadoipestransporte(String validadoipestransporte) {
		this.validadoipestransporte = validadoipestransporte;
	}

	public String getErrorAsignacionTransporte() {
		return errorAsignacionTransporte;
	}

	public void setErrorAsignacionTransporte(String errorAsignacionTransporte) {
		this.errorAsignacionTransporte = errorAsignacionTransporte;
	}

}
